version: "3"

services:
  api:
    container_name: flask-api
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
